// <auto-generated />
using Eventmanagement4._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eventmanagement4._0.Migrations
{
    [DbContext(typeof(Data_customer))]
    partial class Data_customerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eventmangement_4._0.Model.customer_base.customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("customer_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("post_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefphone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("customer");
                });


            modelBuilder.Entity("Eventmangement_4._0.Model.items.main_items", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("customer_id")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("customer_name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("land")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("place")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("post_code")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("street")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("telefphone_number")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("website")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ID");

                b.ToTable("customer");
            });
#pragma warning restore 612, 618
        }
    }
}
